---
- name: Tap ethereum formula repository
  when: install_type == "package"
  homebrew_tap:
    name: ethereum/ethereum
    state: present
  tags:
    - install
    - package
    - darwin

- name: Install geth homebrew package
  when: install_type == "package"
  homebrew:
    name: ethereum
    state: present
  tags:
    - install
    - package
    - darwin
